/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/en001.glb -t -k -E -R -f 
*/

import * as THREE from "three";
import React, { JSX } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    ["900mm"]: THREE.Mesh;
    ["900mm_1"]: THREE.Mesh;
    ["900mm_2"]: THREE.Mesh;
    ["900mm_3"]: THREE.Mesh;
    ["900mm_4"]: THREE.Mesh;
    ["900mm_5"]: THREE.Mesh;
    ["900mm_6"]: THREE.Mesh;
    ["900mm_7"]: THREE.Mesh;
    ["900mm_8"]: THREE.Mesh;
    ["900mm_9"]: THREE.Mesh;
    ["900mm_10"]: THREE.Mesh;
    ["900mm_11"]: THREE.Mesh;
    ["900mm_12"]: THREE.Mesh;
    ["900mm_13"]: THREE.Mesh;
    ["900mm_14"]: THREE.Mesh;
    ["900mm_15"]: THREE.Mesh;
    ["900mm001"]: THREE.Mesh;
    ["900mm001_1"]: THREE.Mesh;
    ["900mm001_2"]: THREE.Mesh;
    ["900mm001_3"]: THREE.Mesh;
    ["900mm001_4"]: THREE.Mesh;
    ["900mm001_5"]: THREE.Mesh;
    ["900mm001_6"]: THREE.Mesh;
    ["900mm001_7"]: THREE.Mesh;
    ["900mm001_8"]: THREE.Mesh;
    ["900mm001_9"]: THREE.Mesh;
    ["900mm001_10"]: THREE.Mesh;
    ["900mm001_11"]: THREE.Mesh;
    ["900mm001_12"]: THREE.Mesh;
    ["900mm001_13"]: THREE.Mesh;
    ["900mm001_14"]: THREE.Mesh;
    ["900mm001_15"]: THREE.Mesh;
    ["900mm006"]: THREE.Mesh;
    ["900mm006_1"]: THREE.Mesh;
    ["900mm006_2"]: THREE.Mesh;
    ["900mm006_3"]: THREE.Mesh;
    ["900mm006_4"]: THREE.Mesh;
    ["900mm006_5"]: THREE.Mesh;
    ["900mm006_6"]: THREE.Mesh;
    ["900mm006_7"]: THREE.Mesh;
    ["900mm006_8"]: THREE.Mesh;
    ["900mm006_9"]: THREE.Mesh;
    ["900mm006_10"]: THREE.Mesh;
    ["900mm006_11"]: THREE.Mesh;
    ["900mm006_12"]: THREE.Mesh;
    ["900mm006_13"]: THREE.Mesh;
    ["900mm006_14"]: THREE.Mesh;
    ["900mm006_15"]: THREE.Mesh;
    ["8x2700"]: THREE.Mesh;
    ["8x2700_1"]: THREE.Mesh;
    ["8x2700_2"]: THREE.Mesh;
    ["8x2700_3"]: THREE.Mesh;
    ["8x2700_4"]: THREE.Mesh;
    ["8x2700_5"]: THREE.Mesh;
    ["8x2700_6"]: THREE.Mesh;
    ["8x2700_7"]: THREE.Mesh;
    ["8x2700_8"]: THREE.Mesh;
    ["8x2700_9"]: THREE.Mesh;
    ["8x2700_10"]: THREE.Mesh;
    ["8x2700_11"]: THREE.Mesh;
    ["8x2700_12"]: THREE.Mesh;
    ["8x2700_13"]: THREE.Mesh;
    ["8x2700_14"]: THREE.Mesh;
    ["8x2700_15"]: THREE.Mesh;
    ["8x2700_16"]: THREE.Mesh;
    ["8x2700_17"]: THREE.Mesh;
    ["8x2700_18"]: THREE.Mesh;
    ["เหล็กกล่อง_100*50*3134"]: THREE.Mesh;
    ["เหล็กกล่อง_100*50*3134_1"]: THREE.Mesh;
    ["เหล็กกล่อง_100*50*3134_2"]: THREE.Mesh;
    ["เหล็กกล่อง_100*50*3134_3"]: THREE.Mesh;
    ["เหล็กกล่อง_100*50*3134_4"]: THREE.Mesh;
    ["เหล็กกล่อง_100*50*3134_5"]: THREE.Mesh;
    ["เหล็กกล่อง_100*50*3134_6"]: THREE.Mesh;
    ["เหล็กกล่อง_100*50*3134_7"]: THREE.Mesh;
    ["เหล็กกล่อง_100*50*3134_8"]: THREE.Mesh;
    ["เหล็กกล่อง_100*50*3134_9"]: THREE.Mesh;
    ["เหล็กกล่อง_100*50*3134_10"]: THREE.Mesh;
    ["เหล็กกล่อง_100*50*3134_11"]: THREE.Mesh;
    ["เหล็กกล่อง_100*50*3134_12"]: THREE.Mesh;
    ["เหล็กกล่อง_100*50*3134_13"]: THREE.Mesh;
  };
  materials: {
    ["Concrete, Cast In Situ"]: THREE.MeshStandardMaterial;
    ["Concrete, Cast-in-Place gray"]: THREE.MeshStandardMaterial;
    ["Concrete - Cast-in-Place Concrete - 35 MPa"]: THREE.MeshStandardMaterial;
    ปูนฉาบ: THREE.MeshStandardMaterial;
    ["Default Wall"]: THREE.MeshStandardMaterial;
    ["Gypsum Wall Board"]: THREE.MeshStandardMaterial;
    Wood: THREE.MeshStandardMaterial;
    Aluminium: THREE.MeshStandardMaterial;
    Glass: THREE.MeshStandardMaterial;
    Laminate: THREE.MeshStandardMaterial;
    Steel: THREE.MeshStandardMaterial;
    ["Default Wall.001"]: THREE.MeshStandardMaterial;
    พื้นขัดมัน: THREE.MeshStandardMaterial;
    Aluminum: THREE.MeshStandardMaterial;
    ["Default Light Source"]: THREE.MeshStandardMaterial;
    ["Metal Sheet"]: THREE.MeshStandardMaterial;
    ["Concrete, Cast In Situ.001"]: THREE.MeshStandardMaterial;
    ["Concrete, Cast-in-Place gray.001"]: THREE.MeshStandardMaterial;
    ["Concrete - Cast-in-Place Concrete - 35 MPa.001"]: THREE.MeshStandardMaterial;
    ["Glass.001"]: THREE.MeshStandardMaterial;
    ["ปูนฉาบ.001"]: THREE.MeshStandardMaterial;
    ["Default Wall.002"]: THREE.MeshStandardMaterial;
    ["Aluminum.001"]: THREE.MeshStandardMaterial;
    ["Wood.001"]: THREE.MeshStandardMaterial;
    ["Aluminium.001"]: THREE.MeshStandardMaterial;
    ["Laminate.001"]: THREE.MeshStandardMaterial;
    ["Gypsum Wall Board.001"]: THREE.MeshStandardMaterial;
    ["Steel.001"]: THREE.MeshStandardMaterial;
    พื้นกระเบื้องปูห้องน้: THREE.MeshStandardMaterial;
    ["พื้นขัดมัน.001"]: THREE.MeshStandardMaterial;
    ["พื้น F6"]: THREE.MeshStandardMaterial;
    ["Mirror 26BF207"]: THREE.MeshStandardMaterial;
    ["Concrete, Cast In Situ.002"]: THREE.MeshStandardMaterial;
    ["Concrete, Cast-in-Place gray.002"]: THREE.MeshStandardMaterial;
    ["Concrete - Cast-in-Place Concrete - 35 MPa.002"]: THREE.MeshStandardMaterial;
    ["Glass.002"]: THREE.MeshStandardMaterial;
    ["ปูนฉาบ.002"]: THREE.MeshStandardMaterial;
    ["Default Wall.003"]: THREE.MeshStandardMaterial;
    ["Aluminum.002"]: THREE.MeshStandardMaterial;
    ["Laminate.002"]: THREE.MeshStandardMaterial;
    ["Aluminium.002"]: THREE.MeshStandardMaterial;
    ["Wood.002"]: THREE.MeshStandardMaterial;
    ["Gypsum Wall Board.002"]: THREE.MeshStandardMaterial;
    ["พื้น F6.001"]: THREE.MeshStandardMaterial;
    พื้นกระเบื้องปูห้อง: THREE.MeshStandardMaterial;
    ["พื้นขัดมัน.002"]: THREE.MeshStandardMaterial;
    ["Steel.002"]: THREE.MeshStandardMaterial;
    ["Mirror 26BF207.001"]: THREE.MeshStandardMaterial;
    ["Resinflex + Resinil - Profilitec - Beige - P32"]: THREE.MeshStandardMaterial;
    ["Aluminum - Profilitec - Natural - AN"]: THREE.MeshStandardMaterial;
    ["Concrete, Cast-in-Place gray.003"]: THREE.MeshStandardMaterial;
    ["Concrete - Cast-in-Place Concrete - 35 MPa.003"]: THREE.MeshStandardMaterial;
    ["Concrete, Cast In Situ.003"]: THREE.MeshStandardMaterial;
    ["ปูนฉาบ.003"]: THREE.MeshStandardMaterial;
    ["Default Wall.004"]: THREE.MeshStandardMaterial;
    ["Glass.003"]: THREE.MeshStandardMaterial;
    ["Aluminum.003"]: THREE.MeshStandardMaterial;
    ["Laminate.003"]: THREE.MeshStandardMaterial;
    ["Aluminium.003"]: THREE.MeshStandardMaterial;
    ["Wood.003"]: THREE.MeshStandardMaterial;
    ["Gypsum Wall Board.003"]: THREE.MeshStandardMaterial;
    ["พื้นขัดมัน.003"]: THREE.MeshStandardMaterial;
    ["พื้นกระเบื้องปูห้อง.001"]: THREE.MeshStandardMaterial;
    ["Steel.003"]: THREE.MeshStandardMaterial;
    ["Default Light Source.001"]: THREE.MeshStandardMaterial;
    ["Acrylic Green"]: THREE.MeshStandardMaterial;
    ["Mirror 26BF207.002"]: THREE.MeshStandardMaterial;
    ["Steel ASTM A500, Grade B, Rectangular and Square"]: THREE.MeshStandardMaterial;
    ["Concrete, Cast-in-Place gray.004"]: THREE.MeshStandardMaterial;
    ["Concrete - Cast-in-Place Concrete - 35 MPa.004"]: THREE.MeshStandardMaterial;
    ["Metal Deck"]: THREE.MeshStandardMaterial;
    ["ปูนฉาบ.004"]: THREE.MeshStandardMaterial;
    ["Default Wall.005"]: THREE.MeshStandardMaterial;
    ["Concrete Masonry Units"]: THREE.MeshStandardMaterial;
    ["Concrete, Cast In Situ.004"]: THREE.MeshStandardMaterial;
    ["Glass.004"]: THREE.MeshStandardMaterial;
    ["Aluminum.004"]: THREE.MeshStandardMaterial;
    ["Laminate.004"]: THREE.MeshStandardMaterial;
    ["Default Light Source.002"]: THREE.MeshStandardMaterial;
    ["Steel.004"]: THREE.MeshStandardMaterial;
    ["Acrylic Green.001"]: THREE.MeshStandardMaterial;
  };
};

export default function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/en001.glb") as unknown as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group
        name="EN00101"
        position={[-1.048, 1.989, 0.37]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.3}
      >
        <mesh
          name="900mm"
          geometry={nodes["900mm"].geometry}
          material={materials["Concrete, Cast In Situ"]}
        />
        <mesh
          name="900mm_1"
          geometry={nodes["900mm_1"].geometry}
          material={materials["Concrete, Cast-in-Place gray"]}
        />
        <mesh
          name="900mm_2"
          geometry={nodes["900mm_2"].geometry}
          material={materials["Concrete - Cast-in-Place Concrete - 35 MPa"]}
        />
        <mesh
          name="900mm_3"
          geometry={nodes["900mm_3"].geometry}
          material={materials.ปูนฉาบ}
        />
        <mesh
          name="900mm_4"
          geometry={nodes["900mm_4"].geometry}
          material={materials["Default Wall"]}
        />
        <mesh
          name="900mm_5"
          geometry={nodes["900mm_5"].geometry}
          material={materials["Gypsum Wall Board"]}
        />
        <mesh
          name="900mm_6"
          geometry={nodes["900mm_6"].geometry}
          material={materials.Wood}
        />
        <mesh
          name="900mm_7"
          geometry={nodes["900mm_7"].geometry}
          material={materials.Aluminium}
        />
        <mesh
          name="900mm_8"
          geometry={nodes["900mm_8"].geometry}
          material={materials.Glass}
        />
        <mesh
          name="900mm_9"
          geometry={nodes["900mm_9"].geometry}
          material={materials.Laminate}
        />
        <mesh
          name="900mm_10"
          geometry={nodes["900mm_10"].geometry}
          material={materials.Steel}
        />
        <mesh
          name="900mm_11"
          geometry={nodes["900mm_11"].geometry}
          material={materials["Default Wall.001"]}
        />
        <mesh
          name="900mm_12"
          geometry={nodes["900mm_12"].geometry}
          material={materials.พื้นขัดมัน}
        />
        <mesh
          name="900mm_13"
          geometry={nodes["900mm_13"].geometry}
          material={materials.Aluminum}
        />
        <mesh
          name="900mm_14"
          geometry={nodes["900mm_14"].geometry}
          material={materials["Default Light Source"]}
        />
        <mesh
          name="900mm_15"
          geometry={nodes["900mm_15"].geometry}
          material={materials["Metal Sheet"]}
        />
      </group>
      <group
        name="EN00102"
        position={[-0.486, 5.831, -1.125]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.3}
      >
        <mesh
          name="900mm001"
          geometry={nodes["900mm001"].geometry}
          material={materials["Concrete, Cast In Situ.001"]}
        />
        <mesh
          name="900mm001_1"
          geometry={nodes["900mm001_1"].geometry}
          material={materials["Concrete, Cast-in-Place gray.001"]}
        />
        <mesh
          name="900mm001_2"
          geometry={nodes["900mm001_2"].geometry}
          material={materials["Concrete - Cast-in-Place Concrete - 35 MPa.001"]}
        />
        <mesh
          name="900mm001_3"
          geometry={nodes["900mm001_3"].geometry}
          material={materials["Glass.001"]}
        />
        <mesh
          name="900mm001_4"
          geometry={nodes["900mm001_4"].geometry}
          material={materials["ปูนฉาบ.001"]}
        />
        <mesh
          name="900mm001_5"
          geometry={nodes["900mm001_5"].geometry}
          material={materials["Default Wall.002"]}
        />
        <mesh
          name="900mm001_6"
          geometry={nodes["900mm001_6"].geometry}
          material={materials["Aluminum.001"]}
        />
        <mesh
          name="900mm001_7"
          geometry={nodes["900mm001_7"].geometry}
          material={materials["Wood.001"]}
        />
        <mesh
          name="900mm001_8"
          geometry={nodes["900mm001_8"].geometry}
          material={materials["Aluminium.001"]}
        />
        <mesh
          name="900mm001_9"
          geometry={nodes["900mm001_9"].geometry}
          material={materials["Laminate.001"]}
        />
        <mesh
          name="900mm001_10"
          geometry={nodes["900mm001_10"].geometry}
          material={materials["Gypsum Wall Board.001"]}
        />
        <mesh
          name="900mm001_11"
          geometry={nodes["900mm001_11"].geometry}
          material={materials["Steel.001"]}
        />
        <mesh
          name="900mm001_12"
          geometry={nodes["900mm001_12"].geometry}
          material={materials.พื้นกระเบื้องปูห้องน้}
        />
        <mesh
          name="900mm001_13"
          geometry={nodes["900mm001_13"].geometry}
          material={materials["พื้นขัดมัน.001"]}
        />
        <mesh
          name="900mm001_14"
          geometry={nodes["900mm001_14"].geometry}
          material={materials["พื้น F6"]}
        />
        <mesh
          name="900mm001_15"
          geometry={nodes["900mm001_15"].geometry}
          material={materials["Mirror 26BF207"]}
        />
      </group>
      <group
        name="EN00103"
        position={[-0.467, 9.43, -1.263]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.3}
      >
        <mesh
          name="900mm006"
          geometry={nodes["900mm006"].geometry}
          material={materials["Concrete, Cast In Situ.002"]}
        />
        <mesh
          name="900mm006_1"
          geometry={nodes["900mm006_1"].geometry}
          material={materials["Concrete, Cast-in-Place gray.002"]}
        />
        <mesh
          name="900mm006_2"
          geometry={nodes["900mm006_2"].geometry}
          material={materials["Concrete - Cast-in-Place Concrete - 35 MPa.002"]}
        />
        <mesh
          name="900mm006_3"
          geometry={nodes["900mm006_3"].geometry}
          material={materials["Glass.002"]}
        />
        <mesh
          name="900mm006_4"
          geometry={nodes["900mm006_4"].geometry}
          material={materials["ปูนฉาบ.002"]}
        />
        <mesh
          name="900mm006_5"
          geometry={nodes["900mm006_5"].geometry}
          material={materials["Default Wall.003"]}
        />
        <mesh
          name="900mm006_6"
          geometry={nodes["900mm006_6"].geometry}
          material={materials["Aluminum.002"]}
        />
        <mesh
          name="900mm006_7"
          geometry={nodes["900mm006_7"].geometry}
          material={materials["Laminate.002"]}
        />
        <mesh
          name="900mm006_8"
          geometry={nodes["900mm006_8"].geometry}
          material={materials["Aluminium.002"]}
        />
        <mesh
          name="900mm006_9"
          geometry={nodes["900mm006_9"].geometry}
          material={materials["Wood.002"]}
        />
        <mesh
          name="900mm006_10"
          geometry={nodes["900mm006_10"].geometry}
          material={materials["Gypsum Wall Board.002"]}
        />
        <mesh
          name="900mm006_11"
          geometry={nodes["900mm006_11"].geometry}
          material={materials["พื้น F6.001"]}
        />
        <mesh
          name="900mm006_12"
          geometry={nodes["900mm006_12"].geometry}
          material={materials.พื้นกระเบื้องปูห้อง}
        />
        <mesh
          name="900mm006_13"
          geometry={nodes["900mm006_13"].geometry}
          material={materials["พื้นขัดมัน.002"]}
        />
        <mesh
          name="900mm006_14"
          geometry={nodes["900mm006_14"].geometry}
          material={materials["Steel.002"]}
        />
        <mesh
          name="900mm006_15"
          geometry={nodes["900mm006_15"].geometry}
          material={materials["Mirror 26BF207.001"]}
        />
      </group>
      <group
        name="EN00104"
        position={[-1.973, 13.376, 2.474]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.3}
      >
        <mesh
          name="8x2700"
          geometry={nodes["8x2700"].geometry}
          material={materials["Resinflex + Resinil - Profilitec - Beige - P32"]}
        />
        <mesh
          name="8x2700_1"
          geometry={nodes["8x2700_1"].geometry}
          material={materials["Aluminum - Profilitec - Natural - AN"]}
        />
        <mesh
          name="8x2700_2"
          geometry={nodes["8x2700_2"].geometry}
          material={materials["Concrete, Cast-in-Place gray.003"]}
        />
        <mesh
          name="8x2700_3"
          geometry={nodes["8x2700_3"].geometry}
          material={materials["Concrete - Cast-in-Place Concrete - 35 MPa.003"]}
        />
        <mesh
          name="8x2700_4"
          geometry={nodes["8x2700_4"].geometry}
          material={materials["Concrete, Cast In Situ.003"]}
        />
        <mesh
          name="8x2700_5"
          geometry={nodes["8x2700_5"].geometry}
          material={materials["ปูนฉาบ.003"]}
        />
        <mesh
          name="8x2700_6"
          geometry={nodes["8x2700_6"].geometry}
          material={materials["Default Wall.004"]}
        />
        <mesh
          name="8x2700_7"
          geometry={nodes["8x2700_7"].geometry}
          material={materials["Glass.003"]}
        />
        <mesh
          name="8x2700_8"
          geometry={nodes["8x2700_8"].geometry}
          material={materials["Aluminum.003"]}
        />
        <mesh
          name="8x2700_9"
          geometry={nodes["8x2700_9"].geometry}
          material={materials["Laminate.003"]}
        />
        <mesh
          name="8x2700_10"
          geometry={nodes["8x2700_10"].geometry}
          material={materials["Aluminium.003"]}
        />
        <mesh
          name="8x2700_11"
          geometry={nodes["8x2700_11"].geometry}
          material={materials["Wood.003"]}
        />
        <mesh
          name="8x2700_12"
          geometry={nodes["8x2700_12"].geometry}
          material={materials["Gypsum Wall Board.003"]}
        />
        <mesh
          name="8x2700_13"
          geometry={nodes["8x2700_13"].geometry}
          material={materials["พื้นขัดมัน.003"]}
        />
        <mesh
          name="8x2700_14"
          geometry={nodes["8x2700_14"].geometry}
          material={materials["พื้นกระเบื้องปูห้อง.001"]}
        />
        <mesh
          name="8x2700_15"
          geometry={nodes["8x2700_15"].geometry}
          material={materials["Steel.003"]}
        />
        <mesh
          name="8x2700_16"
          geometry={nodes["8x2700_16"].geometry}
          material={materials["Default Light Source.001"]}
        />
        <mesh
          name="8x2700_17"
          geometry={nodes["8x2700_17"].geometry}
          material={materials["Acrylic Green"]}
        />
        <mesh
          name="8x2700_18"
          geometry={nodes["8x2700_18"].geometry}
          material={materials["Mirror 26BF207.002"]}
        />
      </group>
      <group
        name="EN001RF"
        position={[0.023, 17.637, 0.292]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.3}
      >
        <mesh
          name="เหล็กกล่อง_100*50*3134"
          geometry={nodes["เหล็กกล่อง_100*50*3134"].geometry}
          material={
            materials["Steel ASTM A500, Grade B, Rectangular and Square"]
          }
        />
        <mesh
          name="เหล็กกล่อง_100*50*3134_1"
          geometry={nodes["เหล็กกล่อง_100*50*3134_1"].geometry}
          material={materials["Concrete, Cast-in-Place gray.004"]}
        />
        <mesh
          name="เหล็กกล่อง_100*50*3134_2"
          geometry={nodes["เหล็กกล่อง_100*50*3134_2"].geometry}
          material={materials["Concrete - Cast-in-Place Concrete - 35 MPa.004"]}
        />
        <mesh
          name="เหล็กกล่อง_100*50*3134_3"
          geometry={nodes["เหล็กกล่อง_100*50*3134_3"].geometry}
          material={materials["Metal Deck"]}
        />
        <mesh
          name="เหล็กกล่อง_100*50*3134_4"
          geometry={nodes["เหล็กกล่อง_100*50*3134_4"].geometry}
          material={materials["ปูนฉาบ.004"]}
        />
        <mesh
          name="เหล็กกล่อง_100*50*3134_5"
          geometry={nodes["เหล็กกล่อง_100*50*3134_5"].geometry}
          material={materials["Default Wall.005"]}
        />
        <mesh
          name="เหล็กกล่อง_100*50*3134_6"
          geometry={nodes["เหล็กกล่อง_100*50*3134_6"].geometry}
          material={materials["Concrete Masonry Units"]}
        />
        <mesh
          name="เหล็กกล่อง_100*50*3134_7"
          geometry={nodes["เหล็กกล่อง_100*50*3134_7"].geometry}
          material={materials["Concrete, Cast In Situ.004"]}
        />
        <mesh
          name="เหล็กกล่อง_100*50*3134_8"
          geometry={nodes["เหล็กกล่อง_100*50*3134_8"].geometry}
          material={materials["Glass.004"]}
        />
        <mesh
          name="เหล็กกล่อง_100*50*3134_9"
          geometry={nodes["เหล็กกล่อง_100*50*3134_9"].geometry}
          material={materials["Aluminum.004"]}
        />
        <mesh
          name="เหล็กกล่อง_100*50*3134_10"
          geometry={nodes["เหล็กกล่อง_100*50*3134_10"].geometry}
          material={materials["Laminate.004"]}
        />
        <mesh
          name="เหล็กกล่อง_100*50*3134_11"
          geometry={nodes["เหล็กกล่อง_100*50*3134_11"].geometry}
          material={materials["Default Light Source.002"]}
        />
        <mesh
          name="เหล็กกล่อง_100*50*3134_12"
          geometry={nodes["เหล็กกล่อง_100*50*3134_12"].geometry}
          material={materials["Steel.004"]}
        />
        <mesh
          name="เหล็กกล่อง_100*50*3134_13"
          geometry={nodes["เหล็กกล่อง_100*50*3134_13"].geometry}
          material={materials["Acrylic Green.001"]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/en001.glb");
