export const buildings = [
  {
    id: 0,
    name: "Building A",
    height: "6.2m",
    floors: 5,
    occupancy: 82,
    energy: 71,
    temp: 23.4,
    status: "Operational",
    systems: { hvac: "Active", security: "Active", elevator: "Active" },
    floorInfo: [
      { name: "Floor 1", occupancy: 78, temp: 23.1, power: 12.4, alerts: 0 },
      { name: "Floor 2", occupancy: 82, temp: 23.6, power: 13.1, alerts: 1 },
      { name: "Floor 3", occupancy: 86, temp: 23.9, power: 14.0, alerts: 0 },
      { name: "Floor 4", occupancy: 79, temp: 23.2, power: 12.8, alerts: 2 },
      { name: "Roof", occupancy: 15, temp: 26.4, power: 9.6, alerts: 0 },
    ],
  },
  {
    id: 1,
    name: "Building B",
    height: "8.4m",
    floors: 8,
    occupancy: 76,
    energy: 64,
    temp: 24.1,
    status: "Operational",
    systems: { hvac: "Active", security: "Active", elevator: "Maintenance" },
  },
];
